
spring:
  http:
      encoding:
        force: true
        charset: UTF-8
  freemarker:
      # 设置模板后缀名
      suffix: .ftl
      # 设置文档类型
      content-type: text/html
      # 设置页面编码格式
      charset: UTF-8
      # 设置页面缓存
      cache: false
      # 设置ftl文件路径
      template-loader-path: classpath:/templates
      # 绝对定位需要
      request-context-attribute: request
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: hcroot
      password: hcroot123456
      url: jdbc:mysql://47.244.222.243:3506/simpleDb?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:/com/xtkj/mapper/*.xml
  type-aliases-package: com.xtkj.dao